version: '3'
services:
  vue-docker-test:
    build: .
    ports:
      - 2435:8080
      - 2436:8000
    volumes:
      - .:/app
    container_name: vue-docker-test
    env_file:
      - ./.env.local
    tty: true